// Code generated by tygo. DO NOT EDIT.

//////////
// source: user.go

import type * as common from "../../../common"

export interface UserListQuery extends common.PaginatedQuery {
    search?: string
    emails?: string[]
    birthdate?: common.DateRange
}
export interface UserCreate {
    email: string
    name: string
    password: string
    birthdate?: string
}
export interface UserUpdate {
    name?: string
    password?: string
    birthdate?: string
}
export interface PasswordChange {
    old_password: string
    new_password: string
}
export interface LoginCredentials {
    email: string
    password: string
}
