// Code generated by tygo. DO NOT EDIT.

//////////
// source: article.go

export interface Article {
    id: number /* uint */
    created_at: string /* RFC3339 */
    updated_at: string /* RFC3339 */
    title: string
    content: string
    author: string
    category?: string
    tags?: string
    likes: number /* int */
    dislikes: number /* int */
}
