// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package tables

import (
	"gorm.io/cli/gorm/field"
)

var OpLog = struct {
	ID          field.String
	ObjectType  field.String
	ObjectId    field.String
	Operation   field.String
	Result      field.String
	Description field.String
	NewData     field.String
	OldData     field.String
	Timestamp   field.Time
	User        field.String
	Ip          field.String
	Times       field.Number[uint32]
}{
	ID:          field.String{}.WithColumn("id"),
	ObjectType:  field.String{}.WithColumn("object_type"),
	ObjectId:    field.String{}.WithColumn("object_id"),
	Operation:   field.String{}.WithColumn("operation"),
	Result:      field.String{}.WithColumn("result"),
	Description: field.String{}.WithColumn("description"),
	NewData:     field.String{}.WithColumn("new_data"),
	OldData:     field.String{}.WithColumn("old_data"),
	Timestamp:   field.Time{}.WithColumn("timestamp"),
	User:        field.String{}.WithColumn("user"),
	Ip:          field.String{}.WithColumn("ip"),
	Times:       field.Number[uint32]{}.WithColumn("times"),
}
