// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package tables

import (
	"gorm.io/cli/gorm/field"
)

var Article = struct {
	ID        field.Number[uint]
	CreatedAt field.Time
	UpdatedAt field.Time
	Title     field.String
	Content   field.String
	Author    field.String
	Category  field.String
	Tags      field.String
	Likes     field.Number[int]
	Dislikes  field.Number[int]
}{
	ID:        field.Number[uint]{}.WithColumn("id"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
	Title:     field.String{}.WithColumn("title"),
	Content:   field.String{}.WithColumn("content"),
	Author:    field.String{}.WithColumn("author"),
	Category:  field.String{}.WithColumn("category"),
	Tags:      field.String{}.WithColumn("tags"),
	Likes:     field.Number[int]{}.WithColumn("likes"),
	Dislikes:  field.Number[int]{}.WithColumn("dislikes"),
}
