// Code generated by tygo. DO NOT EDIT.

//////////
// source: article.go

import type * as common from "../../../common"

export interface ArticleCreate {
    title: string
    content: string
    category?: string
    tags?: string
}
export interface ArticleUpdate {
    title?: string
    content?: string
    category?: string
    tags?: string
}
export interface ArticleListQuery extends common.PaginatedQuery {
    search?: string
    author?: string
    category?: string
}
export interface ArticleLikeAction {
    action: string
}
