// Code generated by tygo. DO NOT EDIT.

//////////
// source: comment.go

import type * as common from "../../../common"

export interface CommentCreate {
    biz_type: string
    biz_id: string
    content: string
    author: string
    parent_id?: number /* uint */
}
export interface CommentUpdate {
    content?: string
}
export interface CommentListQuery extends common.PaginatedQuery {
    biz_type: string
    biz_id: string
    author?: string
    parent_id?: number /* uint */
}
