// Code generated by tygo. DO NOT EDIT.

//////////
// source: oplog.go

export interface OpLog {
    id: string
    object_type: string
    object_id: string
    operation: string
    result: string
    description?: string
    new_data?: string
    old_data?: string
    timestamp: string /* RFC3339 */
    user?: string
    ip?: string
    times: number /* uint32 */
}
