// Code generated by tygo. DO NOT EDIT.

//////////
// source: comment.go

import type * as types from "../types"

export interface Comment extends types.ObjectInfo {
    id: number /* uint */
    created_at: string /* RFC3339 */
    updated_at: string /* RFC3339 */
    content: string
    author: string
    parent_id?: number /* uint */
}

//////////
// source: oplog.go

export interface OpLog extends types.ObjectInfo, types.OpLogBase {
    id: string
    new_data?: string
    old_data?: string
    timestamp: string /* RFC3339 */
    times: number /* uint32 */
}
