// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package db

import (
	"gorm.io/cli/gorm/field"
)

var User = struct {
	Email     field.String
	Name      field.String
	Password  field.String
	Birthdate field.String
	CreatedAt field.Time
	UpdatedAt field.Time
}{
	Email:     field.String{}.WithColumn("email"),
	Name:      field.String{}.WithColumn("name"),
	Password:  field.String{}.WithColumn("password"),
	Birthdate: field.String{}.WithColumn("birthdate"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
}
