// Code generated by tygo. DO NOT EDIT.

//////////
// source: api.go

import type { Result } from "@ayonli/jsext/result"
export type AsyncResult<T> = Promise<Result<T>>

export interface ApiResult<T extends any> {
    success: boolean
    code: number /* int */
    data?: T
    message?: string
}

//////////
// source: misc.go

export interface DateRange {
    start?: string
    end?: string
}

//////////
// source: pagination.go

export interface PaginatedQuery {
    page: number /* int */
    page_size: number /* int */
}
export interface PaginatedResult<T extends any> {
    total: number /* int */
    list: T[]
}
