// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package tables

import (
	"gorm.io/cli/gorm/field"
)

var Comment = struct {
	ID        field.Number[uint]
	CreatedAt field.Time
	UpdatedAt field.Time
	BizType   field.String
	BizId     field.String
	Content   field.String
	Author    field.String
	ParentId  field.Number[uint]
}{
	ID:        field.Number[uint]{}.WithColumn("id"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
	BizType:   field.String{}.WithColumn("biz_type"),
	BizId:     field.String{}.WithColumn("biz_id"),
	Content:   field.String{}.WithColumn("content"),
	Author:    field.String{}.WithColumn("author"),
	ParentId:  field.Number[uint]{}.WithColumn("parent_id"),
}
