// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package tables

import (
	"github.com/ayonli/bilingo/domains/user/models"
	"gorm.io/cli/gorm/field"
)

var Author = struct {
	User      field.Struct[models.User]
	Email     field.String
	Bio       field.String
	Publisher field.String
}{
	User:      field.Struct[models.User]{}.WithName("User"),
	Email:     field.String{}.WithColumn("email"),
	Bio:       field.String{}.WithColumn("bio"),
	Publisher: field.String{}.WithColumn("publisher"),
}
