// Code generated by tygo. DO NOT EDIT.

//////////
// source: oplog.go

import type * as common from "../../../common"

export interface OpLogData {
    object_type: string
    object_id: string
    operation: string
    description?: string
    result: string
    new_data: object
    old_data: object
    timestamp?: string /* RFC3339 */ // Manually set timestamp if needed
    user?: string
    ip?: string
}
export interface OpLogListQuery extends common.PaginatedQuery {
    object_type: string
    object_id: string
}
