// Code generated by tygo. DO NOT EDIT.

//////////
// source: comment.go

import type * as common from "@/common"

export interface CommentCreate extends ObjectInfo {
    content: string
    author: string
    parent_id?: number /* uint */
}
export interface CommentUpdate {
    content?: string
}
export interface CommentListQuery extends common.PaginatedQuery, ObjectInfo {
    author?: string
    parent_id?: number /* uint */
}

//////////
// source: common.go

export interface ObjectInfo {
    object_type: string
    object_id: string
}

//////////
// source: oplog.go

export interface OpLogBase {
    operation: string
    description?: string
    result: string
    user?: string
    ip?: string
}
export interface OpLogData extends ObjectInfo, OpLogBase {
    new_data: object
    old_data: object
    timestamp?: string /* RFC3339 */ // Manually set timestamp if needed
}
export interface OpLogListQuery extends common.PaginatedQuery, ObjectInfo {
}
