// Code generated by tygo. DO NOT EDIT.

//////////
// source: author.go

export interface Author {
    user: User
    email: string
    bio?: string
    publisher?: string
}

//////////
// source: user.go

export interface User {
    email: string
    name: string
    password?: string
    birthdate?: string
    created_at: string /* RFC3339 */
    updated_at: string /* RFC3339 */
}
