// Code generated by tygo. DO NOT EDIT.

//////////
// source: comment.go

export interface Comment {
    id: number /* uint */
    created_at: string /* RFC3339 */
    updated_at: string /* RFC3339 */
    /**
     * Add your fields here
     */
    biz_type: string
    biz_id: string
    content: string
    author: string
    parent_id?: number /* uint */
}
